// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCARTqs53qnZuM1L0yyS_rM0K2iemvNlM',
    appId: '1:435099489700:web:c1053c84d717c9539b5d31',
    messagingSenderId: '435099489700',
    projectId: 'trip-together-0102',
    authDomain: 'trip-together-0102.firebaseapp.com',
    storageBucket: 'trip-together-0102.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Yb5qiHMQKcUd_IM1eF_LRrcj5M6urCw',
    appId: '1:435099489700:android:561d420851d440f09b5d31',
    messagingSenderId: '435099489700',
    projectId: 'trip-together-0102',
    storageBucket: 'trip-together-0102.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtb9Gt5ZAELTJxvfxvIoqZaqHpcikstk8',
    appId: '1:435099489700:ios:8f5abe8815fe3c489b5d31',
    messagingSenderId: '435099489700',
    projectId: 'trip-together-0102',
    storageBucket: 'trip-together-0102.appspot.com',
    iosBundleId: 'com.dariawiencierz.tripTogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtb9Gt5ZAELTJxvfxvIoqZaqHpcikstk8',
    appId: '1:435099489700:ios:489500bdeeb3613b9b5d31',
    messagingSenderId: '435099489700',
    projectId: 'trip-together-0102',
    storageBucket: 'trip-together-0102.appspot.com',
    iosBundleId: 'com.dariawiencierz.tripTogether.RunnerTests',
  );
}
